- README.rst
- galaxy.yml
Signed-off-by: Paul Belanger <pabelanger@redhat.com>
> Updates for new repo location

- plugins/modules/nxos_igmp_interface.py
- tests/integration/targets/nxos_igmp_interface/tests/common/sanity.yaml
Signed-off-by: CaptTrews <capttrews@gmail.com>
> Updated from network content collector

- requirements.txt
- test-requirements.txt
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/402
- New Module Pull Request
```paste below
```
> Add requirements for tests

- test-requirements.txt
> Add pytest as a requirement

- plugins/module_utils/network/nxos/facts/acl_interfaces/acl_interfaces.py
- tests/integration/targets/nxos_acl_interfaces/templates/populate_config.cfg
- tests/integration/targets/nxos_acl_interfaces/tests/cli/deleted.yml
- tests/integration/targets/nxos_acl_interfaces/tests/cli/merged.yml
- tests/integration/targets/nxos_acl_interfaces/tests/cli/overridden.yml
- tests/integration/targets/nxos_acl_interfaces/tests/cli/parsed.yml
- tests/integration/targets/nxos_acl_interfaces/tests/cli/populate_acl.yaml
- tests/integration/targets/nxos_acl_interfaces/tests/cli/populate_config.yaml
- tests/integration/targets/nxos_acl_interfaces/tests/cli/remove_config.yaml
- tests/integration/targets/nxos_acl_interfaces/tests/cli/replaced.yml
- tests/integration/targets/nxos_acl_interfaces/tests/cli/rtt.yml
- Some test changes + a facts fix.
nxos_acl_interfaces
> Streamline tests and a small facts fix

- tests/integration/targets/nxos_bgp_neighbor_af/tests/common/sanity.yaml
- tests/integration/targets/nxos_evpn_vni/tests/common/sanity.yaml
Fixes the following 2 CI issues:
- https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_15/15/3f6432304ca747a7eecff56a9abaf03210f505cf/check/ansible-test-network-integration-nxos-cli-python36/64732bd/controller/ara-report/reports/fa539e68-23de-4eed-b3cd-ee9b59461212.html
- https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_15/15/3f6432304ca747a7eecff56a9abaf03210f505cf/check/ansible-test-network-integration-nxos-cli-python36/64732bd/controller/ara-report/reports/e6ec1734-962d-42c5-9515-69cdebb8ae53.html
targets/nxos_evpn_vni
targets/nxos_bgp_neighbor_af
> Fix CI issues

- plugins/module_utils/network/nxos/config/acls/acls.py
- tests/integration/targets/nxos_acls/tests/cli/deleted.yml
- tests/unit/modules/network/nxos/test_nxos_acls.py
Updated 'deleted' state behaviour and changed scope
nxos_acls
> Updated deleted state for nxos_acls

- plugins/module_utils/network/nxos/argspec/l2_interfaces/l2_interfaces.py
- plugins/module_utils/network/nxos/config/l2_interfaces/l2_interfaces.py
- plugins/modules/nxos_l2_interfaces.py
- tests/integration/targets/nxos_l2_interfaces/defaults/main.yaml
- tests/integration/targets/nxos_l2_interfaces/tasks/cli.yaml
- tests/integration/targets/nxos_l2_interfaces/tasks/nxapi.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/_populate_config.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/_remove_config.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/deleted.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/empty_config.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/gathered.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/merged.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/overridden.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/parsed.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/rendered.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/replaced.yaml
- tests/integration/targets/nxos_l2_interfaces/vars/main.yml
> Add new states to nxos_l2_interfaces

- plugins/modules/nxos_acls.py
Removed metadata 'preview' and updated version_added to 1.0.0
nxos_acls
> Documentation fix for nxos_acls

- plugins/module_utils/network/nxos/argspec/lacp/lacp.py
- plugins/module_utils/network/nxos/config/lacp/lacp.py
- plugins/modules/nxos_lacp.py
- tests/integration/targets/nxos_lacp/defaults/main.yaml
- tests/integration/targets/nxos_lacp/tasks/main.yaml
- tests/integration/targets/nxos_lacp/tasks/nxapi.yaml
- tests/integration/targets/nxos_lacp/tests/common/_populate_config.yaml
- tests/integration/targets/nxos_lacp/tests/common/_remove_config.yaml
- tests/integration/targets/nxos_lacp/tests/common/deleted.yaml
- tests/integration/targets/nxos_lacp/tests/common/empty_config.yaml
- tests/integration/targets/nxos_lacp/tests/common/gathered.yaml
- tests/integration/targets/nxos_lacp/tests/common/merged.yaml
- tests/integration/targets/nxos_lacp/tests/common/parsed.yaml
- tests/integration/targets/nxos_lacp/tests/common/rendered.yaml
- tests/integration/targets/nxos_lacp/tests/common/replaced.yaml
- tests/integration/targets/nxos_lacp/vars/main.yml
> Add new states to nxos_lacp

- plugins/module_utils/network/nxos/argspec/lag_interfaces/lag_interfaces.py
- plugins/module_utils/network/nxos/config/lag_interfaces/lag_interfaces.py
- plugins/module_utils/network/nxos/facts/lag_interfaces/lag_interfaces.py
- plugins/modules/nxos_lag_interfaces.py
- tests/integration/targets/nxos_lag_interfaces/defaults/main.yaml
- tests/integration/targets/nxos_lag_interfaces/tasks/cli.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/_populate_config.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/_remove_config.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/deleted.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/empty_config.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/gathered.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/merged.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/overridden.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/parsed.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/rendered.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/replaced.yaml
- tests/integration/targets/nxos_lag_interfaces/vars/main.yml
> Add new states for nxos_lag_interfaces

- plugins/module_utils/network/nxos/argspec/lacp_interfaces/lacp_interfaces.py
- plugins/module_utils/network/nxos/config/lacp_interfaces/lacp_interfaces.py
- plugins/module_utils/network/nxos/facts/lacp_interfaces/lacp_interfaces.py
- plugins/modules/nxos_lacp_interfaces.py
- tests/integration/targets/nxos_lacp_interfaces/defaults/main.yaml
- tests/integration/targets/nxos_lacp_interfaces/tasks/cli.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/_populate_config.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/_remove_config.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/deleted.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/empty_config.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/gathered.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/merged.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/overridden.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/parsed.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/rendered.yaml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/replaced.yaml
- tests/integration/targets/nxos_lacp_interfaces/vars/main.yml
> Add new states to nxos_lacp_interfaces

- plugins/module_utils/network/nxos/argspec/hsrp_interfaces/hsrp_interfaces.py
- plugins/module_utils/network/nxos/config/hsrp_interfaces/hsrp_interfaces.py
- plugins/modules/nxos_hsrp_interfaces.py
- tests/integration/targets/nxos_hsrp_interfaces/defaults/main.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tasks/cli.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tasks/main.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tasks/nxapi.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/_populate_config.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/_remove_config.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/deleted.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/empty_config.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/gathered.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/merged.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/overridden.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/parsed.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/rendered.yaml
- tests/integration/targets/nxos_hsrp_interfaces/tests/common/replaced.yaml
- tests/integration/targets/nxos_hsrp_interfaces/vars/main.yml
Related to #36
nxos_hsrp_interfaces
> Add new states to nxos_hsrp_interfaces

- plugins/module_utils/network/nxos/config/l2_interfaces/l2_interfaces.py
- tests/integration/targets/nxos_l2_interfaces/tests/common/replaced.yaml
> Fix issue with state replaced

- README.md
- README.rst
- galaxy.yml
documentation
```paste below
```
> update nxos readme

- tests/integration/targets/nxos_file_copy/fixtures/data.cfg
- tests/integration/targets/nxos_file_copy/tasks/main.yaml
- tests/integration/targets/nxos_file_copy/tests/cli/negative.yaml
- tests/integration/targets/nxos_file_copy/tests/cli/sanity.yaml
> nxos_file_copy test fixes

- plugins/module_utils/network/nxos/argspec/interfaces/interfaces.py
- plugins/module_utils/network/nxos/config/interfaces/interfaces.py
- plugins/module_utils/network/nxos/facts/interfaces/interfaces.py
- plugins/modules/nxos_interfaces.py
- tests/integration/targets/nxos_interfaces/defaults/main.yaml
- tests/integration/targets/nxos_interfaces/tasks/cli.yaml
- tests/integration/targets/nxos_interfaces/tasks/nxapi.yaml
- tests/integration/targets/nxos_interfaces/tests/common/_populate_config.yaml
- tests/integration/targets/nxos_interfaces/tests/common/_remove_config.yaml
- tests/integration/targets/nxos_interfaces/tests/common/empty_config.yaml
- tests/integration/targets/nxos_interfaces/tests/common/gathered.yaml
- tests/integration/targets/nxos_interfaces/tests/common/parsed.yaml
- tests/integration/targets/nxos_interfaces/tests/common/rendered.yaml
- tests/integration/targets/nxos_interfaces/vars/main.yml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/_populate_config.yaml
> Add new states to nxos_interfaces

- tests/integration/targets/nxos_interfaces/tests/common/_remove_config.yaml
> Cleanup loopback interfaces properly

- plugins/modules/nxos_devicealias.py
- plugins/modules/nxos_vsan.py
- plugins/modules/nxos_zone_zoneset.py
> Add symlinks to mds modules

- test-requirements.txt
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
Add test requirement coverage==4.5.4
> [cisco.nxos] Add test requirement for coverage

- plugins/httpapi/nxos.py
Show a warning if they try and just move on.
httpapi/nxos
> Ignore enable in httpapi as it is not supported on nxapi

- plugins/action/nxos.py
- tests/integration/targets/nxos_smoke/defaults/main.yaml
- tests/integration/targets/nxos_smoke/meta/main.yml
- tests/integration/targets/nxos_smoke/tasks/cli.yaml
- tests/integration/targets/nxos_smoke/tasks/main.yaml
- tests/integration/targets/nxos_smoke/tasks/nxapi.yaml
- tests/integration/targets/nxos_smoke/tests/cli/misc_tests.yaml
- tests/integration/targets/nxos_smoke/tests/common/common_config.yaml
- tests/integration/targets/nxos_smoke/tests/common/common_utils.yaml
- tests/integration/targets/nxos_smoke/tests/common/misc_tests.yaml
- Add nxos_smoke
targets/nxos_smoke
> Add nxos_smoke tests back

- plugins/doc_fragments/nxos.py
I also threw in the removal while I was in there. Feel free to argue about the date.
See also ansible-collections/arista.eos#52
doc_fragments/nxos
> Woah, we really should not be promoting provider for NX-API

- README.md
> add link to contributor guide etc

- changelogs/CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/config.yaml
- changelogs/fragments/99-add-change-log-1.0.0.yaml
*  Add changelog file for 1.0.0 release genereated
using https://github.com/ansible-community/antsibull-changelog
```paste below
```
> Add changelog files

- README.md
Signed-off-by: Paul Belanger <pabelanger@redhat.com>
> Change references of master to main

- tox.ini
To provide actionable feedback for formatting failures.
> [nxos] Provide feedback on linters failure

- changelogs/fragments/116-add-FQCN-for-documentation
- plugins/modules/nxos_facts.py
- plugins/modules/nxos_interface.py
- plugins/modules/nxos_ping.py
- plugins/modules/nxos_snmp_traps.py
- plugins/modules/nxos_vrf_interface.py
- plugins/modules/nxos_vtp_domain.py
- plugins/modules/nxos_vtp_password.py
- plugins/modules/nxos_vtp_version.py
- plugins/modules/nxos_vxlan_vtep.py
add FQCN to M() references
ansible-collections/overview#89
> add FQCN to M() references

- tests/unit/modules/network/nxos/test_nxos_ospfv2.py
> Sort process dicts before rendering commands

- changelogs/fragments/142-N9K-multisite.yaml
- plugins/module_utils/network/nxos/argspec/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/nxos/config/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/nxos/facts/l3_interfaces/l3_interfaces.py
- plugins/modules/nxos_bgp_af.py
- plugins/modules/nxos_bgp_neighbor.py
- plugins/modules/nxos_bgp_neighbor_af.py
- plugins/modules/nxos_l3_interfaces.py
- plugins/modules/nxos_vxlan_vtep.py
- plugins/modules/nxos_vxlan_vtep_vni.py
- tests/integration/targets/nxos_bgp_af/tests/common/multisite.yaml
- tests/integration/targets/nxos_bgp_neighbor/tests/common/multisite.yaml
- tests/integration/targets/nxos_bgp_neighbor_af/tests/common/multisite.yaml
- tests/integration/targets/nxos_l3_interfaces/tests/common/multisite.yaml
- tests/integration/targets/nxos_l3_interfaces/vars/main.yml
- tests/integration/targets/nxos_vxlan_vtep/tests/common/multisite.yaml
- tests/integration/targets/nxos_vxlan_vtep_vni/tests/common/multisite.yaml
- tests/unit/modules/network/nxos/fixtures/nxos_bgp/config.cfg
- tests/unit/modules/network/nxos/fixtures/nxos_vxlan_vtep/config.cfg
- tests/unit/modules/network/nxos/fixtures/nxos_vxlan_vtep_vni/config.cfg
- tests/unit/modules/network/nxos/test_nxos_bgp_af.py
- tests/unit/modules/network/nxos/test_nxos_bgp_neighbor.py
- tests/unit/modules/network/nxos/test_nxos_bgp_neighbor_af.py
- tests/unit/modules/network/nxos/test_nxos_l3_interfaces.py
- tests/unit/modules/network/nxos/test_nxos_vxlan_vtep.py
- tests/unit/modules/network/nxos/test_nxos_vxlan_vtep_vni.py
Adding NXOS multisite support.
nxos_bgp_af
nxos_bgp_neighbor
nxos_bgp_neighbor_af
nxos_vxlan_vtep
nxos_vxlan_vtep_vni
nxos_l3_interfaces
> N9K Multisite Support

- changelogs/fragments/fix_nxos_banner_with_spaces.yaml
- plugins/modules/nxos_banner.py
- tests/integration/targets/nxos_banner/tasks/main.yaml
- tests/integration/targets/nxos_banner/tests/common/sanity.yaml
- tests/unit/modules/network/nxos/test_nxos_banner.py
> Preserve white spaces in input banner text

- changelogs/fragments/fix_nxos_smu.yaml
- meta/runtime.yml
- plugins/modules/nxos_smu.py
- tests/sanity/ignore-2.9.txt
Fixes #115 
The smu module passes smu path along with smu name for activate and commit steps and is not required.
modules/nxos_smu.py
> Fix for nxos smu issue

- changelogs/CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/161-transfer_protocol_file_copy.yaml
- changelogs/fragments/add_nxos_ospfv3.yaml
- changelogs/fragments/doc_updates.yaml
- changelogs/fragments/fix_lacp_interfaces_mode_facts_parsing.yaml
- changelogs/fragments/fix_nxos_acl_interfaces.yaml
- changelogs/fragments/fix_nxos_banner_with_spaces.yaml
- changelogs/fragments/fix_nxos_lag_interfaces.yaml
- changelogs/fragments/fix_nxos_ospfv2.yaml
- changelogs/fragments/fix_nxos_smu.yaml
> Prepare for v1.2.0 release

- changelogs/fragments/fix_nxos_rpm.yaml
- plugins/modules/nxos_rpm.py
Fix for issue in rpm module
- Fixes the show commands checks at various stages of restart smu installation
- Fixes the interactive cli issue for "install remove" command for restart smu
- Fixes the check for return code for reload smu through network_cli
- Fixes the iteration of return code check in case of reload smu
module/nxos_rpm.py
> Fix for rpm module issues

- changelogs/CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/add_fex_fabric_l2_inteerfaces.yaml
- changelogs/fragments/add_nxos_ospf_interfaces.yaml
- changelogs/fragments/fix_nxos_rpm.yaml
- changelogs/fragments/fix_vlan_diff.yaml
- changelogs/fragments/vlans-fabricpath-mode-regex.yaml
> Add changelog for 1.3.0

- docs/cisco.nxos.nxos_user_module.rst
> Update doc for nxos_user

- changelogs/CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_nxos_lag_interfaces.yaml
- changelogs/fragments/fix_ospf_process_id.yaml
- changelogs/fragments/galaxy-version.yaml
- changelogs/fragments/support_nxos_user_mds.yaml
> Add changelog for 1.3.1

- changelogs/config.yaml
Add a new section in changelogs for documentation changes
None(?)
changelogs/config.yaml
> Add new section in changelog - `doc_changes`

- changelogs/fragments/fix_nxos_l3_interfaces_tag.yaml
- plugins/module_utils/network/nxos/config/l3_interfaces/l3_interfaces.py
- tests/unit/modules/network/nxos/test_nxos_l3_interfaces.py
- Fixes #197 
nxos_l3_interfaces.py
> Allow tag updates with state replaced

- changelogs/fragments/fix_interface_context.yaml
- plugins/module_utils/network/nxos/facts/interfaces/interfaces.py
- plugins/module_utils/network/nxos/facts/l2_interfaces/l2_interfaces.py
- plugins/module_utils/network/nxos/facts/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/nxos/facts/lacp_interfaces/lacp_interfaces.py
- tests/integration/targets/nxos_l2_interfaces/tests/common/parsed.yaml
- tests/integration/targets/nxos_l2_interfaces/vars/main.yml
- tests/integration/targets/nxos_lacp_interfaces/tests/common/parsed.yaml
- tests/unit/modules/network/nxos/test_nxos_interfaces.py
- tests/unit/modules/network/nxos/test_nxos_l3_interfaces.py
- Fixes #195
- Fixes #122 
nxos_interfaces
nxos_l2_interfaces
nxos_l3_interfaces
nxos_lacp_interfaces
> Parse interface contexts correctly

- changelogs/fragments/fix_nxos_facts.yaml
- plugins/module_utils/network/nxos/facts/legacy/base.py
> nxos_facts: fix traceback while parsing ps_info data for newer releases

- README.md
- changelogs/fragments/add_default_options.yaml
- docs/cisco.nxos.nxos_devicealias_module.rst
- docs/cisco.nxos.nxos_igmp_module.rst
- docs/cisco.nxos.nxos_l3_interfaces_module.rst
- docs/cisco.nxos.nxos_linkagg_module.rst
- docs/cisco.nxos.nxos_nxapi_module.rst
- docs/cisco.nxos.nxos_udld_module.rst
- docs/cisco.nxos.nxos_vsan_module.rst
- docs/cisco.nxos.nxos_vxlan_vtep_module.rst
- docs/cisco.nxos.nxos_zone_zoneset_module.rst
- plugins/module_utils/network/nxos/argspec/l3_interfaces/l3_interfaces.py
- plugins/module_utils/network/nxos/nxos.py
- plugins/modules/nxos_igmp.py
- plugins/modules/nxos_l3_interfaces.py
- plugins/modules/nxos_linkagg.py
- plugins/modules/nxos_nxapi.py
- plugins/modules/nxos_udld.py
- plugins/modules/storage/nxos_devicealias.py
- plugins/modules/storage/nxos_vsan.py
- plugins/modules/storage/nxos_zone_zoneset.py
- Upgrading to ansible-base==2.10.4 exposed some sanity test failures.
(https://gist.github.com/NilashishC/e79c680bd410967f75ef98368dfea5a2#file-ansible-test-sanity-with-2-10-4)
- This patch attempts to fix those.
> Update argspecs with default values

- changelogs/fragments/fix_nxos_bgp_global.yaml
- docs/cisco.nxos.nxos_bgp_global_module.rst
- plugins/module_utils/network/nxos/argspec/bgp_global/bgp_global.py
- plugins/module_utils/network/nxos/config/bgp_global/bgp_global.py
- plugins/module_utils/network/nxos/rm_templates/bgp_global.py
- plugins/modules/nxos_bgp_global.py
- tests/unit/modules/network/nxos/test_nxos_bgp_global.py
- Fixes #240
- Fixes #241 
nxos_bgp_global.py
> Configure neighbor timers properly and add support for BFD

- README.md
- changelogs/fragments/fix_nxos_sanity.yaml
- meta/runtime.yml
- plugins/module_utils/network/nxos/config/acls/acls.py
- plugins/module_utils/network/nxos/config/static_routes/static_routes.py
- plugins/modules/nxos_igmp_interface.py
- plugins/modules/nxos_l3_interface.py
- plugins/modules/nxos_vxlan_vtep_vni.py
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.9.txt
> Fix failures with ansible-test-sanity-docker-.*

- changelogs/fragments/add_caching_support.yaml
- plugins/cliconf/nxos.py
- plugins/terminal/nxos.py
- tests/integration/targets/nxos_smoke/tasks/cli.yaml
- tests/integration/targets/nxos_smoke/tests/common/caching.yaml
- Targets https://github.com/ansible-collections/ansible.netcommon/issues/73
- Add nxos cliconf specific bits for caching feature
plugins/cliconf/nxos.py
> Add support for single_user_mode

- changelogs/fragments/update_unit_test_imports.yaml
- tests/unit/modules/network/nxos/test_nxos_bgp_global.py
- tests/unit/modules/network/nxos/test_nxos_ospf_interfaces.py
- tests/unit/modules/network/nxos/test_nxos_ospfv2.py
- tests/unit/modules/network/nxos/test_nxos_ospfv3.py
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/180/
- Update unit tests to align with RMBase reorg.
> Update unit test imports

- changelogs/fragments/pim_version_added.yaml
- plugins/modules/nxos_pim_interface.py
- Add missing version_added for hello_interval_ms key in nxos_pim_interface.
> Add version_added for new key

- changelogs/fragments/259-remove_tests_sanity_requirements.yml
- tests/sanity/requirements.txt
https://github.com/ansible-collections/overview/issues/43
> Remove tests/sanity/requirements.txt

- changelogs/fragments/add_state_purged.yaml
- docs/cisco.nxos.nxos_interfaces_module.rst
- plugins/module_utils/network/nxos/argspec/interfaces/interfaces.py
- plugins/module_utils/network/nxos/config/interfaces/interfaces.py
- plugins/modules/nxos_interfaces.py
- tests/integration/targets/nxos_interfaces/tests/common/purged.yaml
- tests/unit/modules/network/nxos/test_nxos_interfaces.py
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/84
nxos_interfaces.py
> Add state purged in nxos_interfaces

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/259-remove_tests_sanity_requirements.yml
- changelogs/fragments/add_state_purged.yaml
- changelogs/fragments/fix_j2_2_10.yaml
- changelogs/fragments/fix_nxos_acls.yaml
- changelogs/fragments/no_log_fix.yaml
- changelogs/fragments/pim_version_added.yaml
> Prepare for v2.1.0 release

- .pre-commit-config.yaml
> Bump collection_prep to 0.9.2 in pre-commit

- changelogs/fragments/275-add_ignore_txt.yml
- tests/sanity/ignore-2.12.txt
Please, after merge, add 2.11 to the test matrix (I didn't find it)
https://github.com/ansible-collections/overview/issues/45#issuecomment-813821100
> Add ignore-2.12.txt

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/275-add_ignore_txt.yml
- changelogs/fragments/update_requirement.yaml
> Prepare for v2.1.1 release

- changelogs/fragments/cahing_tests.yaml
- tests/integration/targets/nxos_smoke/tasks/cli.yaml
- tests/integration/targets/nxos_smoke/tests/common/caching.yaml
Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/256
> Use FQCN in caching tests

- changelogs/fragments/268_available_network_resources.yaml
- plugins/module_utils/network/nxos/argspec/facts/facts.py
- plugins/modules/nxos_facts.py
- tests/integration/targets/nxos_facts/tests/common/all_facts.yaml
Signed-off-by: Rohit Thakur <rohitthakur2590@outlook.com>
resolve: https://github.com/ansible-collections/cisco.nxos/issues/268
nxos_facts
```paste below
```
> NXOS: available_network_resource implementation in nxos_facts

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/268_available_network_resources.yaml
- changelogs/fragments/add_nxos_route_maps.yaml
- changelogs/fragments/cahing_tests.yaml
> Prepare for v2.2.0 release

- changelogs/fragments/docs_facts.yaml
- docs/cisco.nxos.nxos_facts_module.rst
> Update docs to include available_network_resources

- changelogs/fragments/bgp_nbr_af.yaml
- plugins/module_utils/network/nxos/argspec/bgp_neighbor_address_family/bgp_neighbor_address_family.py
- plugins/module_utils/network/nxos/config/bgp_neighbor_address_family/bgp_neighbor_address_family.py
- plugins/module_utils/network/nxos/rm_templates/bgp_neighbor_address_family.py
- tests/integration/targets/nxos_bgp_neighbor_address_family/vars/main.yml
- tests/unit/modules/network/nxos/test_nxos_bgp_neighbor_address_family.py
Fixes #281 
nxos_bgp_neighbor_address_family.py
> Fix how send_community option is handled

- changelogs/fragments/fix_ospf_interfaces.yaml
- docs/cisco.nxos.nxos_ospf_interfaces_module.rst
- plugins/module_utils/network/nxos/argspec/ospf_interfaces/ospf_interfaces.py
- plugins/module_utils/network/nxos/config/ospf_interfaces/ospf_interfaces.py
- plugins/module_utils/network/nxos/rm_templates/ospf_interfaces.py
- plugins/modules/nxos_ospf_interfaces.py
- tests/unit/modules/network/nxos/test_nxos_ospf_interfaces.py
- Fixes #264 
nxos_ospf_interfaces.py
> Assorted fixes for passive_interface option

- changelogs/fragments/pre_sort.yaml
- plugins/module_utils/network/nxos/facts/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/nxos/facts/ospf_interfaces/ospf_interfaces.py
- tests/unit/modules/network/nxos/test_nxos_vxlan_vtep_vni.py
> Pre-sort list of dictionaries in facts

- changelogs/fragments/docs_spelling_correction.yaml
- docs/cisco.nxos.nxos_bgp_address_family_module.rst
- docs/cisco.nxos.nxos_bgp_global_module.rst
- docs/cisco.nxos.nxos_bgp_neighbor_address_family_module.rst
- docs/cisco.nxos.nxos_ospf_interfaces_module.rst
- docs/cisco.nxos.nxos_ospfv2_module.rst
- docs/cisco.nxos.nxos_ospfv3_module.rst
- docs/cisco.nxos.nxos_route_maps_module.rst
- plugins/module_utils/network/nxos/utils/telemetry/telemetry.py
- plugins/modules/nxos_bgp_address_family.py
- plugins/modules/nxos_bgp_global.py
- plugins/modules/nxos_bgp_neighbor_address_family.py
- plugins/modules/nxos_ospf_interfaces.py
- plugins/modules/nxos_ospfv2.py
- plugins/modules/nxos_ospfv3.py
- plugins/modules/nxos_route_maps.py
- tests/integration/targets/nxos_bgp_address_family/tests/common/merged.yaml
- tests/integration/targets/nxos_bgp_address_family/tests/common/overridden.yaml
- tests/integration/targets/nxos_bgp_address_family/tests/common/replaced.yaml
- tests/integration/targets/nxos_bgp_global/tests/common/merged.yaml
- tests/integration/targets/nxos_bgp_neighbor_address_family/tests/common/merged.yaml
- tests/integration/targets/nxos_bgp_neighbor_address_family/tests/common/overridden.yaml
- tests/integration/targets/nxos_ospf_interfaces/tests/common/merged.yaml
- tests/integration/targets/nxos_ospf_interfaces/tests/common/overridden.yaml
- tests/integration/targets/nxos_ospfv2/tests/common/merged.yaml
- tests/integration/targets/nxos_ospfv2/tests/common/overridden.yaml
- tests/integration/targets/nxos_ospfv3/tests/common/merged.yaml
- tests/integration/targets/nxos_ospfv3/tests/common/overridden.yaml
- tests/integration/targets/nxos_route_maps/tests/common/merged.yaml
- tests/integration/targets/nxos_route_maps/tests/common/overridden.yaml
A couple of  _exisiting_ changed to _existing_ 
And took out a redundant doc line
> Spelling glitch and docs update

- README.md
- changelogs/fragments/update_readme_freenode_to_libera.yml
https://github.com/ansible-community/community-topics/issues/19
README.md
> Update README: freenode -> libera.chat

- changelogs/fragments/fix_nxos_bgp_global.yaml
- plugins/module_utils/network/nxos/rm_templates/bgp_global.py
- tests/unit/modules/network/nxos/test_nxos_bgp_global.py
- Fixes #308 
nxos_bgp_global.py
> Render neighbor peer_type command correctly

- changelogs/fragments/nxos_bgp_af.yaml
- docs/cisco.nxos.nxos_bgp_address_family_module.rst
- plugins/module_utils/network/nxos/argspec/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/nxos/config/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/nxos/rm_templates/bgp_address_family.py
- plugins/modules/nxos_bgp_address_family.py
- tests/unit/modules/network/nxos/test_nxos_bgp_address_family.py
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/302
nxos_bgp_address_family.py
> Add advertise_l2vpn_evpn option

- changelogs/fragments/logging_global_return_values.yaml
- docs/cisco.nxos.nxos_logging_global_module.rst
- plugins/modules/nxos_logging_global.py
> [logging_global] Add return values

- changelogs/fragments/l2_interfaces.yaml
- plugins/module_utils/network/nxos/config/l2_interfaces/l2_interfaces.py
- plugins/module_utils/network/nxos/utils/utils.py
- tests/integration/targets/nxos_l2_interfaces/tests/common/merged.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/overridden.yaml
- tests/integration/targets/nxos_l2_interfaces/tests/common/replaced.yaml
- tests/integration/targets/nxos_l2_interfaces/vars/main.yml
- Fixes #95
nxos_l2_interfaces.py
> [l2_interfaces] convert vlan list to ranges

- changelogs/fragments/nxos_vrf_af_fix.yaml
- plugins/modules/nxos_vrf_af.py
- tests/unit/modules/network/nxos/test_nxos_vrf_af.py
> [vrf_af] do not expand direction  for N9K

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/315-safe-eval-no-concat.yml
- changelogs/fragments/add_nxos_logging_global.yaml
- changelogs/fragments/doc_broken_link.yaml
- changelogs/fragments/l2_interfaces.yaml
- changelogs/fragments/logging_global_return_values.yaml
- changelogs/fragments/nxos_vrf_af_fix.yaml
- changelogs/fragments/prefix_lists.yaml
- changelogs/fragments/static_routes.yaml
> Prepare for v2.5.0

- changelogs/fragments/fix_pylint_issues.yaml
- plugins/modules/nxos_interface_ospf.py
- tests/sanity/ignore-2.12.txt
- tests/unit/modules/network/nxos/test_nxos_acl.py
- tests/unit/modules/network/nxos/test_nxos_acl_interface.py
- tests/unit/modules/network/nxos/test_nxos_interface.py
- tests/unit/modules/network/nxos/test_nxos_nxapi.py
- tests/unit/modules/network/nxos/test_nxos_pim_interface.py
- tests/unit/modules/network/nxos/test_nxos_vlan.py
- tests/unit/modules/network/nxos/test_nxos_vlans.py
- tests/unit/modules/network/nxos/test_nxos_vpc.py
- tests/unit/modules/network/nxos/test_nxos_vpc_interface.py
- tests/unit/modules/network/nxos/test_nxos_vrf.py
> Fix pylint issues

- 2
> Remove dangling changelog fragment

- changelogs/fragments/set_allow_duplicates.yaml
- tests/integration/targets/prepare_nxos_tests/meta/main.yaml
Signed-off-by: GomathiselviS <gomathiselvi@gmail.com>
set allow_duplicates to true in prepare_nxos_tests to support network-ee.
- New Module Pull Request
```paste below
```
> Allow_duplicates for prepare_nxos_tests

- .pre-commit-config.yaml
- docs/cisco.nxos.nxos_acl_interface_module.rst
- docs/cisco.nxos.nxos_acl_module.rst
- docs/cisco.nxos.nxos_bgp_af_module.rst
- docs/cisco.nxos.nxos_bgp_module.rst
- docs/cisco.nxos.nxos_bgp_neighbor_af_module.rst
- docs/cisco.nxos.nxos_bgp_neighbor_module.rst
- docs/cisco.nxos.nxos_interface_module.rst
- docs/cisco.nxos.nxos_interface_ospf_module.rst
- docs/cisco.nxos.nxos_l2_interface_module.rst
- docs/cisco.nxos.nxos_l3_interface_module.rst
- docs/cisco.nxos.nxos_linkagg_module.rst
- docs/cisco.nxos.nxos_lldp_module.rst
- docs/cisco.nxos.nxos_logging_module.rst
- docs/cisco.nxos.nxos_ntp_auth_module.rst
- docs/cisco.nxos.nxos_ntp_module.rst
- docs/cisco.nxos.nxos_ntp_options_module.rst
- docs/cisco.nxos.nxos_ospf_module.rst
- docs/cisco.nxos.nxos_ospf_vrf_module.rst
- docs/cisco.nxos.nxos_smu_module.rst
- docs/cisco.nxos.nxos_static_route_module.rst
- docs/cisco.nxos.nxos_vlan_module.rst
Committed via https://github.com/asottile/all-repos
> Updating collection_prep pre-commit hook to 0.9.4

- changelogs/fragments/fix_facts.yaml
- plugins/module_utils/network/nxos/facts/legacy/base.py
> nxos_facts: Fix KeyError while gathering CDP facts

- changelogs/fragments/nxos_ospf_interfaces.yaml
- docs/cisco.nxos.nxos_ospf_interfaces_module.rst
- docs/cisco.nxos.nxos_ospfv2_module.rst
- docs/cisco.nxos.nxos_ospfv3_module.rst
- plugins/modules/nxos_ospf_interfaces.py
- plugins/modules/nxos_ospfv2.py
- plugins/modules/nxos_ospfv3.py
- Fixes #361
nxos_ospf[v2, v3, _interfaces].py
> [ospf_*] Update description for area_id

- changelogs/fragments/nxos_acls.yaml
- plugins/module_utils/network/nxos/config/acls/acls.py
- tests/integration/targets/nxos_acls/tests/common/rendered.yml
> [acls] fix traceback with port_protocol range

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_facts.yaml
- changelogs/fragments/fix_ospf_interfaces.yaml
- changelogs/fragments/nxos_acls.yaml
- changelogs/fragments/nxos_ntp_global.yaml
- changelogs/fragments/nxos_ospf_interfaces.yaml
- changelogs/fragments/remove_end_play.yaml
- changelogs/fragments/set_allow_duplicates.yaml
> Prepare v2.6.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/nxos_vlans_json.yaml
> Update changelog for v2.6.0

- changelogs/fragments/nxos_telemetry.yaml
- docs/cisco.nxos.nxos_telemetry_module.rst
- plugins/module_utils/network/nxos/argspec/telemetry/telemetry.py
- plugins/module_utils/network/nxos/config/telemetry/telemetry.py
- plugins/modules/nxos_telemetry.py
- tests/integration/targets/nxos_telemetry/tests/common/gathered.yaml
- tests/integration/targets/nxos_telemetry/vars/main.yaml
- tests/unit/modules/network/nxos/test_nxos_telemetry.py
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/371
nxos_telemetry.py
> [telemetry] Add support for state `gathered`

- changelogs/fragments/nxos_logging.yaml
- plugins/module_utils/network/nxos/rm_templates/logging_global.py
- tests/unit/modules/network/nxos/test_nxos_logging_global.py
- Fixes #380 
nxos_logging_global.py
> [logging_global] Fix vlan_mgr not being gathered

- changelogs/fragments/nxos_acls.yaml
- plugins/module_utils/network/nxos/config/acls/acls.py
- tests/integration/targets/nxos_acls/tests/common/merged.yml
- tests/unit/modules/network/nxos/test_nxos_acls.py
> [acls] Updates to existing ACEs can only be done through states `replaced` and `overridden`

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/ignores.yaml
- changelogs/fragments/nxos_acls.yaml
- changelogs/fragments/nxos_logging.yaml
- changelogs/fragments/nxos_vlans.yaml
> Prepare for v2.7.1

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/nxos_acls.yaml
> Prepare for v2.8.1 release

- changelogs/fragments/ignore.yaml
- tests/sanity/ignore-2.10.txt
- tests/sanity/ignore-2.11.txt
- tests/sanity/ignore-2.9.txt
> Add 2.6 ignores

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/ignore.yaml
- changelogs/fragments/nxos_ntp.yaml
- changelogs/fragments/snmp_server_ignore_2.6.yaml
> Prepare for 2.8.2

- changelogs/fragments/nxos_bgp_af.yaml
- docs/cisco.nxos.nxos_bgp_address_family_module.rst
- plugins/module_utils/network/nxos/argspec/bgp_address_family/bgp_address_family.py
- plugins/modules/nxos_bgp_address_family.py
- tests/unit/modules/network/nxos/test_nxos_bgp_address_family.py
- Fixes #385 
nxos_bgp_address_family.py
> [bgp_address_family] add hmm option for redistribute protocol

- docs/cisco.nxos.nxos_facts_module.rst
module: update list of arguments from code
nxos_facts
source :
https://github.com/ansible-collections/cisco.nxos/blob/c29302840ee545c868cd571122ffc34287468529/plugins/module_utils/network/nxos/facts/facts.py
should link to be included in doc ?
```paste below
```
> Docs: update list of available substes

- changelogs/fragments/updates.yaml
- docs/cisco.nxos.nxos_facts_module.rst
- meta/runtime.yml
- plugins/modules/nxos_facts.py
> Updates for v2.9.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/nxos_bgp_af.yaml
- changelogs/fragments/nxos_hostname.yaml
- changelogs/fragments/nxos_snmp_server.yaml
- changelogs/fragments/updates.yaml
> Prepare for v2.9.0

- changelogs/fragments/fix_sanity.yaml
- docs/cisco.nxos.nxos_cliconf.rst
- docs/cisco.nxos.nxos_feature_module.rst
- docs/cisco.nxos.nxos_httpapi.rst
- docs/cisco.nxos.nxos_install_os_module.rst
- docs/cisco.nxos.nxos_netconf.rst
- docs/cisco.nxos.nxos_reboot_module.rst
- plugins/cliconf/nxos.py
- plugins/httpapi/nxos.py
- plugins/netconf/nxos.py
> Fix sanity failures

- changelogs/fragments/sanity.yaml
- docs/cisco.nxos.nxos_cliconf.rst
- docs/cisco.nxos.nxos_hsrp_module.rst
- docs/cisco.nxos.nxos_snmp_host_module.rst
- plugins/cliconf/nxos.py
- plugins/modules/nxos_hsrp.py
- plugins/modules/nxos_snmp_host.py
> Assorted sanity fixes for devel

- changelogs/fragments/ntp_global.yaml
- docs/cisco.nxos.nxos_ntp_global_module.rst
- plugins/module_utils/network/nxos/argspec/ntp_global/ntp_global.py
- plugins/module_utils/network/nxos/rm_templates/ntp_global.py
- plugins/modules/nxos_ntp_global.py
- tests/unit/modules/network/nxos/test_nxos_ntp_global.py
- Fixes #435
nxos_ntp_global.py
> [ntp_global] Alias vrf to use_vrf

- changelogs/fragments/snmp_server.yaml
- docs/cisco.nxos.nxos_snmp_server_module.rst
- plugins/module_utils/network/nxos/argspec/snmp_server/snmp_server.py
- plugins/module_utils/network/nxos/facts/snmp_server/snmp_server.py
- plugins/module_utils/network/nxos/rm_templates/snmp_server.py
- plugins/modules/nxos_snmp_server.py
- tests/unit/modules/network/nxos/test_nxos_snmp_server.py
Fixes #433 
nxos_snmp_server.py
> [snmp_server] Add alias for community

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_nxos_vlans.yaml
- changelogs/fragments/fix_sanity.yaml
- changelogs/fragments/module_docs_support_for_cisco_mds.yaml
- changelogs/fragments/ntp_global.yaml
- changelogs/fragments/runtime.yaml
- changelogs/fragments/sanity.yaml
- changelogs/fragments/snmp_server.yaml
- changelogs/fragments/tox.yaml
> Prepare for release v2.9.1

- README.md
- changelogs/fragments/fix_ci.yaml
- tests/integration/targets/nxos_acl_interfaces/tasks/main.yaml
- tests/integration/targets/nxos_file_copy/tests/cli/negative.yaml
- tests/integration/targets/nxos_file_copy/tests/cli/sanity.yaml
- tests/integration/targets/nxos_file_copy/tests/nxapi/badtransport.yaml
- tests/integration/targets/nxos_lag_interfaces/tasks/main.yaml
- tests/integration/targets/nxos_logging/tests/common/basic.yaml
- tests/integration/targets/nxos_ntp_global/tests/common/merged.yaml
- tests/integration/targets/nxos_ntp_global/tests/common/overridden.yaml
- tests/integration/targets/nxos_ntp_global/tests/common/rendered.yaml
- tests/integration/targets/nxos_ntp_global/tests/common/replaced.yaml
- tests/integration/targets/nxos_ntp_global/vars/main.yml
- tests/integration/targets/nxos_prefix_lists/tests/common/_remove_config.yaml
- tests/integration/targets/nxos_smoke/tasks/cli.yaml
- tests/integration/targets/nxos_smoke/tasks/nxapi.yaml
- tests/integration/targets/nxos_smoke/tests/common/common_utils.yaml
- tests/integration/targets/nxos_snmp_server/tasks/main.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/gathered.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/merged.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/overridden.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/rendered.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/replaced.yaml
- tests/integration/targets/nxos_snmp_server/vars/main.yml
- tests/integration/targets/nxos_telemetry/tasks/main.yaml
- tests/integration/targets/nxos_telemetry/vars/main.yaml
- tests/integration/targets/prepare_nxos_tests/tasks/main.yml
> Fix tests for image upgrade

- changelogs/fragments/nxos_facts.yaml
- docs/cisco.nxos.nxos_facts_module.rst
- plugins/module_utils/network/nxos/argspec/facts/facts.py
- plugins/modules/nxos_facts.py
- tests/integration/targets/nxos_facts/tests/common/default_facts.yaml
> [facts] change default subset to min

- changelogs/fragments/lag_interfaces.yaml
- plugins/module_utils/network/nxos/config/lag_interfaces/lag_interfaces.py
- tests/integration/targets/nxos_lag_interfaces/tests/common/_remove_config.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/merged.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/overridden.yaml
- tests/integration/targets/nxos_lag_interfaces/tests/common/replaced.yaml
- Fixes #452
nxos_lag_interfaces.py
> [lag_interfaces] fix overriden for channels with no members

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_ci.yaml
- changelogs/fragments/lag_interfaces.yaml
- changelogs/fragments/min_netcommon.yaml
- changelogs/fragments/netcommon_ref_update.yaml
- changelogs/fragments/ntp.yaml
- changelogs/fragments/nxos_facts.yaml
- changelogs/fragments/nxos_file_copy.yaml
- changelogs/fragments/nxos_snmp_server.yaml
- changelogs/fragments/nxos_snmp_server_1.yaml
- changelogs/fragments/snmp_server_PR444.yaml
- changelogs/fragments/stderr.yaml
> Prepare for release v3.0.0

- changelogs/fragments/file_copy.yaml
- tests/integration/targets/nxos_file_copy/tests/cli/input_validation.yaml
> Fix file copy test validation message

- changelogs/fragments/file_cp.yaml
- tests/integration/targets/nxos_file_copy/tests/cli/input_validation.yaml
- tests/integration/targets/nxos_hostname/tasks/main.yaml
> GHA CML test updates

- changelogs/fragments/sanity.yaml
- plugins/module_utils/network/nxos/utils/utils.py
- plugins/modules/nxos_nxapi.py
Fixes https://github.com/ansible-collections/cisco.nxos/issues/509
> Fix sanity issues with >2.13 and Python 3.10 

- changelogs/fragments/snmp_server_localized.yaml
- docs/cisco.nxos.nxos_snmp_server_module.rst
- plugins/module_utils/network/nxos/argspec/snmp_server/snmp_server.py
- plugins/module_utils/network/nxos/rm_templates/snmp_server.py
- plugins/modules/nxos_snmp_server.py
- tests/unit/modules/network/nxos/test_nxos_snmp_server.py
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/415
nxos_snmp_server.py
> [snmp_server] support localizedv2_key

- .github/workflows/test.yml
- changelogs/fragments/522.yaml
Add the ansible-lint github action
content quality assurance
tests
N/A
> Add ansible-lint github action

- .github/workflows/test.yml
- changelogs/fragments/523.yaml
Require ansible-lint in all_green
- Content quality
tests
> Require lint

- changelogs/changelog.yaml
- galaxy.yml
Related: https://github.com/ansible/ansible-lint/pull/2197
> Fix two ansible-lint rules

- changelogs/fragments/snmp_server_526.yml
- plugins/module_utils/network/nxos/rm_templates/snmp_server.py
- tests/unit/modules/network/nxos/test_nxos_snmp_server.py
Hello, 
Is there a doc, somewhere, if it exists, on how to run the test locally for this module ?
I'm not very experience with python and unfortunately I can't really spend too much time to debug.
Fix a typo.
Fixes #526
- 
snmp-server
```paste below
```
> [snmp_server] typo trap link Fixes #526

- changelogs/fragments/filecopy_mds.yaml
- docs/cisco.nxos.nxos_file_copy_module.rst
- plugins/modules/nxos_file_copy.py
- Fixes #508 
nxos_file_copy.py
> [file_copy] skip vrf for MDS targets

- changelogs/fragments/mds_docs.yaml
- docs/cisco.nxos.nxos_logging_global_module.rst
- docs/cisco.nxos.nxos_ntp_global_module.rst
- docs/cisco.nxos.nxos_snmp_server_module.rst
- plugins/modules/nxos_logging_global.py
- plugins/modules/nxos_ntp_global.py
- plugins/modules/nxos_snmp_server.py
- Fixes #471 
- Fixes #472 
- Fixes #473 
nxos_ntp_global.py
nxos_logging_global.py
nxos_snmp_server.py
> Update docs for MDS

- tests/integration/targets/nxos_l3_interfaces/tasks/main.yaml
- tests/integration/targets/nxos_snmp_server/tasks/main.yaml
- tests/integration/targets/nxos_telemetry/tasks/main.yaml
Reference: https://ansible-lint.readthedocs.io/en/latest/default_rules/#var-spacing
```paste below
```
> Fix var-spacing rule from ansible-lint

- changelogs/fragments/sanity_fix.yaml
- plugins/cliconf/nxos.py
- plugins/modules/nxos_bgp_neighbor.py
- plugins/modules/nxos_vrf_interface.py
> Fix sanity issues

- docs/cisco.nxos.nxos_telemetry_module.rst
- plugins/modules/nxos_telemetry.py
Fixed typo in Examples
```paste below
```
> fixed typo in docs

- changelogs/fragments/paramiko.yaml
- requirements.txt
~~Not sure if we can do this immediately, just need to create an environment where paramiko > 2.8 actually gets used~~
It looks like this passes?
> Drop pinned paramiko version

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/ospf_subinterface_failure.yaml
- changelogs/fragments/paramiko.yaml
- changelogs/fragments/sanity_fix.yaml
- tests/integration/targets/prepare_nxos_tests/tasks/prepare.yml
> Prepare for release v3.1.1

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/nxos_facts.yaml
> Prepare for v3.1.2

- tests/integration/targets/nxos_install_os/tasks/upgrade/copy_kick_system_images.yaml
- tests/integration/targets/nxos_install_os/tasks/upgrade/install_with_kick.yaml
Reported by ansible-lint, found using eco pipeline.
> Linting fixes

- changelogs/fragments/passwd_lookup.yaml
- tests/integration/targets/nxos_file_copy/tasks/main.yaml
- tests/integration/targets/nxos_telemetry/tasks/main.yaml
> Fix incorrect use of password lookup in tests

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/ignore_2.15.yaml
- changelogs/fragments/l3_interfaces.yaml
- changelogs/fragments/passwd_lookup.yaml
- changelogs/fragments/telemetry.yaml
> Prepare v3.2.0

- changelogs/fragments/nxos_pim.yaml
- docs/cisco.nxos.nxos_pim_module.rst
- plugins/modules/nxos_pim.py
> Fix sanity failure

- changelogs/fragments/nxos_acls.yaml
- plugins/module_utils/network/nxos/facts/acls/acls.py
- tests/unit/modules/network/nxos/test_nxos_acls.py
- Fixes #583
- Fixes #557
- Fixes #529
nxos_acls.py
> [acls] Fix port_protocol parsing and ICMP options

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/nxos_acls.yaml
- changelogs/fragments/nxos_pim.yaml
> Prepare for v4.0.1

- changelogs/fragments/rm_base.yaml
- plugins/module_utils/network/nxos/config/bgp_address_family/bgp_address_family.py
- plugins/module_utils/network/nxos/config/bgp_global/bgp_global.py
- plugins/module_utils/network/nxos/config/bgp_neighbor_address_family/bgp_neighbor_address_family.py
- plugins/module_utils/network/nxos/config/ospf_interfaces/ospf_interfaces.py
- plugins/module_utils/network/nxos/config/ospfv2/ospfv2.py
- plugins/module_utils/network/nxos/config/ospfv3/ospfv3.py
- plugins/module_utils/network/nxos/config/route_maps/route_maps.py
- plugins/module_utils/network/nxos/rm_templates/bgp_address_family.py
- plugins/module_utils/network/nxos/rm_templates/bgp_global.py
- plugins/module_utils/network/nxos/rm_templates/bgp_neighbor_address_family.py
- plugins/module_utils/network/nxos/rm_templates/ospf_interfaces.py
- plugins/module_utils/network/nxos/rm_templates/ospfv2.py
- plugins/module_utils/network/nxos/rm_templates/ospfv3.py
- plugins/module_utils/network/nxos/rm_templates/route_maps.py
The old name will be removed in netcommon 5.0.0
> Redirect ResourceModule to new location

- changelogs/fragments/nxos_snmp_revert.yaml
- tests/integration/targets/nxos_snmp_server/tasks/main.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/overridden.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/replaced.yaml
- tests/integration/targets/nxos_snmp_server/vars/main.yml
> [snmp_server] test updates

- .config/ansible-lint.yml
- changelogs/fragments/nxos_file_copy.yaml
- plugins/modules/nxos_file_copy.py
> [file_copy] fix full remote path generation

- changelogs/fragments/mds.yaml
- docs/cisco.nxos.nxos_facts_module.rst
- plugins/module_utils/network/nxos/facts/facts.py
- plugins/modules/nxos_facts.py
Depends-On: https://github.com/ansible/ansible-zuul-jobs/pull/1747
- This patch allows `gather_network_resources: all` to work for NX-OS on MDS platform.
nxos_facts.py
> [facts] Updates for MDS platform

- changelogs/fragments/command.yaml
- docs/cisco.nxos.nxos_command_module.rst
- plugins/modules/nxos_command.py
- tests/unit/modules/network/nxos/test_nxos_command.py
> [command] do not fail when retries is 0

- changelogs/fragments/acls.yaml
- plugins/terminal/nxos.py
> [acls] detect and fail for duplicate ACE error

- changelogs/fragments/nxos_acls.yaml
- plugins/module_utils/network/nxos/facts/acls/acls.py
- tests/unit/modules/network/nxos/test_nxos_acls.py
> [acls] fix IPv6 prefix to host conversion

- changelogs/fragments/acls_icmp.yaml
- docs/cisco.nxos.nxos_acls_module.rst
- plugins/module_utils/network/nxos/argspec/acls/acls.py
- plugins/module_utils/network/nxos/config/acls/acls.py
- plugins/module_utils/network/nxos/facts/acls/acls.py
- plugins/modules/nxos_acls.py
- tests/unit/modules/network/nxos/test_nxos_acls.py
> [acls] support ICMPv6 options in ACEs

- changelogs/fragments/tests.yaml
- tests/integration/targets/nxos_snmp_server/tasks/main.yaml
- Fix https://github.com/ansible-collections/cisco.nxos/issues/680
> [snmp_server] downstream test fix

- changelogs/fragments/l3.yaml
- plugins/module_utils/network/nxos/config/l3_interfaces/l3_interfaces.py
- tests/unit/modules/network/nxos/test_nxos_l3_interfaces.py
> [l3_interfaces] append tag with state replaced

- changelogs/fragments/terminal.yaml
- plugins/terminal/nxos.py
> [terminal] fix privilege escalation

- changelogs/fragments/fix_docs_static_routes.yaml
- docs/cisco.nxos.nxos_static_routes_module.rst
- plugins/modules/nxos_static_routes.py
> Fix docs for static routes RM.

- changelogs/fragments/overridden.yaml
- docs/cisco.nxos.nxos_bgp_global_module.rst
- docs/cisco.nxos.nxos_lacp_module.rst
- docs/cisco.nxos.nxos_lldp_global_module.rst
- plugins/module_utils/network/nxos/argspec/bgp_global/bgp_global.py
- plugins/module_utils/network/nxos/argspec/lacp/lacp.py
- plugins/module_utils/network/nxos/argspec/lldp_global/lldp_global.py
- plugins/module_utils/network/nxos/config/lacp/lacp.py
- plugins/module_utils/network/nxos/config/lldp_global/lldp_global.py
- plugins/modules/nxos_bgp_global.py
- plugins/modules/nxos_lacp.py
- plugins/modules/nxos_lldp_global.py
- tests/integration/targets/nxos_lacp/tests/common/overridden.yaml
- tests/integration/targets/nxos_lldp_global/tests/common/overridden.yml
- tests/unit/modules/network/nxos/test_nxos_bgp_global.py
> Add support for state overridden where it is missing

- changelogs/fragments/fix_713.yaml
- plugins/module_utils/network/nxos/facts/acls/acls.py
- tests/unit/modules/network/nxos/test_nxos_acls.py
> [acls] Fix parsing error when ACE has source port range

- changelogs/fragments/fix_730.yaml
- plugins/module_utils/network/nxos/config/interfaces/interfaces.py
- tests/unit/modules/network/nxos/test_nxos_interfaces.py
- Fixes #730
nxos_interfaces.py
> [interfaces] re-apply MTU when changing mode to L2

- changelogs/fragments/_health_check_update_docs.yaml
- docs/cisco.nxos.nxos_bgp_address_family_module.rst
- docs/cisco.nxos.nxos_bgp_global_module.rst
- docs/cisco.nxos.nxos_bgp_neighbor_address_family_module.rst
- docs/cisco.nxos.nxos_bgp_templates_module.rst
- docs/cisco.nxos.nxos_ospf_interfaces_module.rst
- docs/cisco.nxos.nxos_ospfv2_module.rst
- docs/cisco.nxos.nxos_ospfv3_module.rst
- plugins/modules/nxos_bgp_address_family.py
- plugins/modules/nxos_bgp_global.py
- plugins/modules/nxos_bgp_neighbor_address_family.py
- plugins/modules/nxos_bgp_templates.py
- plugins/modules/nxos_ospf_interfaces.py
- plugins/modules/nxos_ospfv2.py
- plugins/modules/nxos_ospfv3.py
> Update Docs with examples

- changelogs/fragments/bgp_assorted.yaml
- docs/cisco.nxos.nxos_bgp_global_module.rst
- docs/cisco.nxos.nxos_bgp_neighbor_address_family_module.rst
- docs/cisco.nxos.nxos_fc_interfaces_module.rst
- plugins/module_utils/network/nxos/argspec/bgp_global/bgp_global.py
- plugins/module_utils/network/nxos/argspec/bgp_neighbor_address_family/bgp_neighbor_address_family.py
- plugins/module_utils/network/nxos/config/bgp_global/bgp_global.py
- plugins/module_utils/network/nxos/config/bgp_neighbor_address_family/bgp_neighbor_address_family.py
- plugins/module_utils/network/nxos/facts/bgp_global/bgp_global.py
- plugins/module_utils/network/nxos/facts/bgp_neighbor_address_family/bgp_neighbor_address_family.py
- plugins/module_utils/network/nxos/rm_templates/bgp_global.py
- plugins/module_utils/network/nxos/rm_templates/bgp_neighbor_address_family.py
- plugins/modules/nxos_bgp_global.py
- plugins/modules/nxos_bgp_neighbor_address_family.py
- plugins/modules/nxos_fc_interfaces.py
- tests/unit/modules/network/nxos/test_nxos_bgp_global.py
- tests/unit/modules/network/nxos/test_nxos_bgp_neighbor_address_family.py
- Fixes #741 
nxos_bgp_global.py
nxos_bgp_neighbor_address_family.py
> [bgp] add support for lesser used options

- changelogs/fragments/vtp_version.yaml
- docs/cisco.nxos.nxos_vtp_version_module.rst
- galaxy.yml
- plugins/modules/nxos_vtp_version.py
- Fixes #704 
nxos_vtp_version.py
> [vtp_version] allow VTP version 3

- .ansible-lint
- .ansible-lint-ignore
- changelogs/fragments/acls.yaml
- docs/cisco.nxos.nxos_acls_module.rst
- plugins/module_utils/network/nxos/facts/acls/acls.py
- plugins/modules/nxos_acls.py
- tests/config.yml
- Update example docs for nxos_acls with YAML output.
- Fixes #759 
nxos_acls.py
> [acls] update examples and use YAML output in them for better readibility

- changelogs/fragments/fix_763.yaml
- plugins/module_utils/network/nxos/facts/acls/acls.py
- tests/sanity/ignore-2.17.txt
- tests/unit/modules/network/nxos/test_nxos_acls.py
> [acls] fix ACE parsing error with named source/dest port range

- README.md
- platform_guide.rst
> Move platform guide to this repo

- changelogs/fragments/acls_gather_fix.yml
- plugins/module_utils/network/nxos/facts/acls/acls.py
- tests/unit/modules/network/nxos/test_nxos_acls.py
- Fixes #788 
facts/acls.py
```paste below
```
> [nxos_acls] Fix parsing of aces with range

- .github/workflows/tests.yml
- New Module Pull Request
```paste below
```
> Use ansible-content-actions build-import

- .github/workflows/integration-test.yml
- tests/integration/labs/single.yaml
- Mostly changing the single.yml file to have title as collection full name so it can find and replace later using sed
- Passing the labtitle prefix in integration test
> CML LAB unique name

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/add_restore_support.yaml
- changelogs/fragments/fix_771.yaml
- changelogs/fragments/trivial.yaml
> Prepare release 8.0.0

- changelogs/fragments/fix_820.yaml
- plugins/module_utils/network/nxos/rm_templates/snmp_server.py
- tests/unit/modules/network/nxos/test_nxos_snmp_server.py
- Fixes #820
nxos_snmp_server.py
> [snmp_server] correctly render entity traps

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_820.yaml
- changelogs/fragments/nxos_vrf_global.yml
- galaxy.yml
> Release 9.1.0

- changelogs/fragments/fix_pylint.yaml
- plugins/modules/nxos_ping.py
> Fix pylint unbound var error

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/bugfix_vrf_range_resolution.yml
- changelogs/fragments/lldp_facts.yaml
- changelogs/fragments/readme.yaml
- galaxy.yml
> Prepare release v9.2.1

- changelogs/fragments/ignore_219.yaml
- tests/sanity/ignore-2.19.txt
Fixes the upstream failing nightlies sanity error.
ignore-2.19.txt
```paste below
https://github.com/ansible-collections/cisco.nxos/actions/runs/11023742495/job/30615621234
```
> Add ignore-2.19.txt

- .github/workflows/integration-test.yml
Change workflow to use content actions integration
- CI
> Change workflow

- docs/cisco.nxos.nxos_vrf_address_family_module.rst
Add rst file for vrf_address_family
> Add rst file for vrf_address_family

- tests/integration/targets/nxos_vrf_address_family/tasks/main.yml
Disable VRF Address family role##### ISSUE TYPE
- Test
> Disable VRF Address family role

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/add_vrf_interfaces.yaml
- changelogs/fragments/fix_ana_569.yaml
- changelogs/fragments/ignore_219.yaml
- changelogs/fragments/lag_interfaces_error.yaml
- changelogs/fragments/nxos_facts_cpu_utilization.yaml
- changelogs/fragments/nxos_feature.yaml
- changelogs/fragments/nxos_l2_interfaces.yaml
- changelogs/fragments/nxos_telemetry_overridden.yaml
- changelogs/fragments/purged_user.yaml
- changelogs/fragments/tests_fix.yaml
- changelogs/fragments/vrf_address_fam.yaml
- galaxy.yml
> Release 9.3.0 Prep

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/added_support_peer_switch_cmd.yaml
- changelogs/fragments/ci_logging_global.yaml
- changelogs/fragments/nxos_facts_ipv6.yaml
- changelogs/fragments/test_ci.yaml
- galaxy.yml
> release_prep_9.4.0

- changelogs/fragments/fix_tests.yml
- tests/unit/modules/utils.py
Update test set_module_args for compatibility with new patching method
- Test fix
> Update test set_module_args for compatibility with new patching method

- changelogs/fragments/fix_downstream.yml
- tests/integration/targets/nxos_snmp_server/tasks/main.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/gathered.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/overridden.yaml
- tests/integration/targets/nxos_snmp_server/tests/common/replaced.yaml
- tests/integration/targets/nxos_snmp_server/vars/main.yml
This PR fixes downstream tests for nxos_snmp_server caused due to initial config difference
- Test fix
> Fix downstream tests for snmp server

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/fix_downstream.yml
- changelogs/fragments/fix_tests.yml
- changelogs/fragments/update_hsrp_interfaces.yml
- galaxy.yml
> Release PR 10.1.0

- CHANGELOG.rst
- changelogs/changelog.yaml
- changelogs/fragments/acls_fix.yml
- changelogs/fragments/add_attr_interfaces.yaml
- changelogs/fragments/fix_ci.yaml
- changelogs/fragments/fix_sanity.yaml
- changelogs/fragments/rewrite_l2_interfaces.yml
- galaxy.yml
> Prep release v10.2.0

- README.md
- changelogs/fragments/update_main_readme.yaml
update readme file to reflect 9.4.3 version for Cisco MDS. Fixes #946
> update readme file to reflect 9.4.3 version for Cisco MDS. Fixes #946
