ansible-collections/cisco.nxos

plugins/modules/nxos_banner.py

Fixes an apparent typo in the documentation that explains what the module does.
Changes `nxos/plugins/modules/nxos_banner.py` and replace the word `remote` with `remove`
This change does not add or change any current functionality.  It replaces a word to make the documentation a bit more clear regarding what it actually does.
Before:
```
description:
- This will configure both exec and motd banners on remote devices running Cisco NXOS.
It allows playbooks to add or remote banner text from the active running configuration.
```
After:
```
description:
- This will configure both exec and motd banners on remote devices running Cisco NXOS.
It allows playbooks to add or remove banner text from the active running configuration.
```

Fix typo in module documentation

---

plugins/terminal/nxos.py

- The response received doesn't start with (Error|error), instead in most cases it starts with the last command sent. As a result, the terminal error regex fails to catch it and the task doesn't fail. This PR removes the starts with from the regex.
```
response = b'redistribute bgp 65589 route-map rmap_8\r\r\nError: bgp-65578 is already distributed, Only one is allowed\r\r\nNexus9000v(config-router-vrf)#
```
terminal/nxos.py

Remove starts with from error regex

---

tests/integration/targets/nxos_acl_interfaces/tests/cli/remove_config.yaml

- nxos_acls is sending an extra command in overridden test to remove `NewACLv6`, this is unaccounted for and is a result of improper cleanup in acl_interfaces.
Test failure:
https://object-storage-ca-ymq-1.vexxhost.net/v1/a0b4156a37f9453eb4ec7db5422272df/ansible_22/22/53e8d97b01fbccd727fd935816ab86ca3ba60bef/check/ansible-test-network-integration-nxos-cli-python36/3182342/controller/ara-report/reports/b7c4da90-4bc7-40a9-9b04-fd34659cb276.html
targets/nxos_acl_interfaces

[TEST-FIX] Cleanup nxos_acl_interfaces properly

---

plugins/modules/nxos_user.py
tests/integration/targets/nxos_user/tests/common/basic.yaml

- Fixes https://github.com/ansible-collections/cisco.nxos/issues/27
- Remove superfluous return values from doc string
nxos_user.py

nxos_user should fail when device rejects configured_password

---

plugins/modules/nxos_vrf_interface.py

use normalize_interface as in every other nxos module
affected nxos_vrf_interface modul
tested with nexus 77

use normalize_interface as in every other nxos module

---

plugins/module_utils/network/nxos/argspec/bfd_interfaces/bfd_interfaces.py
plugins/module_utils/network/nxos/config/bfd_interfaces/bfd_interfaces.py
plugins/modules/nxos_bfd_interfaces.py
tests/integration/targets/nxos_bfd_interfaces/defaults/main.yaml
tests/integration/targets/nxos_bfd_interfaces/tasks/cli.yaml
tests/integration/targets/nxos_bfd_interfaces/tasks/main.yaml
tests/integration/targets/nxos_bfd_interfaces/tasks/nxapi.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/_populate_config.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/_remove_config.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/deleted.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/empty_config.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/gathered.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/merged.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/overridden.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/parsed.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/rendered.yaml
tests/integration/targets/nxos_bfd_interfaces/tests/common/replaced.yaml
tests/integration/targets/nxos_bfd_interfaces/vars/main.yml

This also fixes an issue in config code. Since gather_subset was hardcoded to be ['!all', '!min], the platform version returned would always be empty. This patch changes it to ["min"] by default and for non-action states + gathered, it'd be ['!all', '!min'].
nxos_bfd_interfaces.py

Add new states to nxos_bfd_interfaces

---

plugins/module_utils/network/nxos/facts/interfaces/interfaces.py
tests/integration/targets/nxos_interfaces/tests/common/merged.yaml

- #20 
- Concatenating defaults and interface data without a delimiter causes regexes in render_system_defaults() to not work properly.
- For example, the data passed to render_system_defaults() looks something like:
```
no system default switchport
no system default switchport fabricpath
no system default switchport shutdowninterface Ethernet1/1
description TEST
switchport
interface Ethernet1/2
interface Ethernet1/3
interface mgmt0
ip address dhcp
vrf member management
interface loopback8
```
As a result, [this](https://github.com/ansible-collections/cisco.nxos/blob/master/plugins/module_utils/network/nxos/facts/interfaces/interfaces.py#L124) doesn't work as expected. We could have modified the regex as well, but that didn't …

Fix system default generation

---

plugins/action/nxos_file_copy.py
tests/integration/targets/nxos_file_copy/tests/nxapi/badtransport.yaml

Depends-On: https://github.com/ansible-collections/cisco.nxos/pull/52
SUMMARY
The following is the list of changes included in this PR. The fix involves two parts:
bad_transport.yaml - the assert statement was checking for a wrong message. The actual message retuendd from the module is different. So the YAML file is fixed ot check for correct message
nxos_file_copy.py - There are a couple of places in this module where a replace is used with byte string. This is not working in python 3.8. The fix is to change the byte string to a string and then use replace the required string.
ISSUE TYPE
Bugfix Pull Request
COMPONENT NAME
nxos_file_copy
ADDITIONAL INFORMATION
The issue is seen when the test case is executed without any additional steps.

Republish nxos_file_copy changes

---

plugins/httpapi/nxos.py

With delayed connection start, `self._become` _can_ change from the before the request to after. Rather than blindly stripping responses, from the output, decline to include responses whose input was enable.
plugins/httpapi/nxos

httpapi enable issue

---

plugins/terminal/nxos.py

Updated on_become to consistentsly strip whitespace before checking to see if prompt ends with "enable#".
Before, it ran 1 check without strip and 1 check with strip.
plugins/terminal/nxos.py

Updated nxos.py terminal plugin on_become

---

plugins/terminal/nxos.py

- Fixes #54 
- Currently, on_become() raises an exception if feature privilege is disabled even before checking the current privilege level or calling validate_user_role().
- As a result, a "show privilege" output like the following, with ansible_become set to True, results in the task failing. 
```
User name: test_user
Current privilege level: 15
Feature privilege: Disabled
```
- This patch moves this check to the correct place.
terminal/nxos.py
```paste below
```

Check feature privilege status only if priv escalation is required

---

plugins/module_utils/network/nxos/facts/legacy/base.py

SUMMARY
Fixes https://github.com/ansible/ansible/issues/68405
This is the fix for issue in https://github.com/ansible/ansible/issues/68405
The following is the list of changes included in this PR.
nxos/facts/legacy/base.py - While gathering facts, on parsing and populating the interfaces, the data from switch is always treated as list. Because of this in particular scenarios where-in there are no interface, a traceback is seen. The fix now checks if the data is a single interface instance or list and acts accordingly.
ISSUE TYPE
Bugfix Pull Request
COMPONENT NAME
nxos.facts
ADDITIONAL INFORMATION
This issue will be seen while gathering fact when there are no interfaces in default vdc in N7K

Fix for vdc with no interface in N7K

---

plugins/module_utils/network/nxos/config/l3_interfaces/l3_interfaces.py
plugins/module_utils/network/nxos/facts/l2_interfaces/l2_interfaces.py
plugins/module_utils/network/nxos/facts/l3_interfaces/l3_interfaces.py
plugins/modules/nxos_l3_interfaces.py
tests/integration/targets/nxos_l2_interfaces/tests/common/deleted.yaml
tests/integration/targets/nxos_l2_interfaces/tests/common/gathered.yaml
tests/integration/targets/nxos_l2_interfaces/tests/common/merged.yaml
tests/integration/targets/nxos_l2_interfaces/tests/common/rendered.yaml
tests/integration/targets/nxos_l2_interfaces/tests/common/rtt.yaml
tests/integration/targets/nxos_l3_interfaces/tasks/main.yaml
tests/integration/targets/nxos_l3_interfaces/tasks/nxapi.yaml
tests/integration/targets/nxos_l3_interfaces/tests/common/deleted.yaml
tests/integration/targets/nxos_l3_interfaces/tests/common/gathered.yaml
tests/integration/targets/nxos_l3_interfaces/tests/common/merged.yaml
tests/integration/targets/nxos_l3_interfaces/tests/common/overridden.yaml
tests/integration/targets/nxos_l3_interfaces/tests/common/parsed.yaml
tests/integration/targets/nxos_l3_interfaces/tests/common/rendered.yaml
tests/integration/targets/nxos_l3_interfaces/tests/common/replaced.yaml
tests/integration/targets/nxos_l3_interfaces/tests/common/rtt.yaml
tests/integration/targets/nxos_l3_interfaces/vars/main.yml
tests/unit/modules/network/nxos/test_nxos_l3_interfaces.py

* Both default and non-default interfaces are returned now.
* Removes check for reserved interfaces to ensure 100% round-trip
with facts.
* Adds round-trip tests.
* A minor documentation fix.
nxos_l2_interfaces.py
nxos_l3_interfaces.py

Streamline l2_interfaces and l3_interfaces

---

changelogs/102-fix-nxos_interfaces-states.yaml
plugins/module_utils/network/nxos/config/interfaces/interfaces.py
tests/integration/targets/nxos_interfaces/tests/common/replaced.yaml

- Fixes #100 
- `state: replaced` was ignoring negate commands if no new attributes were being added for that interface in the task.
- Since `state: overridden` depends on `state: replaced` it is affected too.
nxos_interfaces.py

Fix nxos_interfaces state overridden & replaced

---

changelogs/fragments/fix_command_key.yaml
plugins/modules/nxos_command.py

- `commands` key accepts both a list of string and a list of dictionaries, as a result, the type of elements should be `raw`,
instead of just `str`.
nxos_command

Element type of commands key has to be raw

---

changelogs/fragments/fix_nxos_user_role.yaml
plugins/modules/nxos_user.py
tests/integration/targets/nxos_user/tests/common/basic.yaml

- Fixes #123 
- The nxos_user module validates the role passed in the task with a predefined list of built-in roles, which becomes a problem when a custom role is used.
- This fix dynamically fetches the list of custom roles from the device and appends it to the predefined list.
nxos_user.py

nxos_user: Do not fail when a custom role is used

---

changelogs/fragments/fix_nxos_acl_interfaces.yaml
plugins/module_utils/network/nxos/facts/acl_interfaces/acl_interfaces.py
tests/unit/modules/network/nxos/test_nxos_acl_interfaces.py

- Fixes #149 
- Existing regexes with "\w+" for parsing ACL names doesn't match all possible strings.
- Includes some overall cleanup of facts code.
nxos_acl_interfaces.py

Fix nxos_acl_interfaces facts parsing

---

changelogs/fragments/fix_nxos_lag_interfaces.yaml
plugins/module_utils/network/nxos/facts/lag_interfaces/lag_interfaces.py
tests/integration/targets/nxos_lag_interfaces/tests/common/parsed.yaml
tests/integration/targets/nxos_lag_interfaces/vars/main.yml

- Fixes #147 
- The regex in facts code was incorrectly parsing the config line that followed "channel-group <group-number> mode <on|active|passive>".
facts/lag_interfaces.py

Fix regex in nxos_lag_interfaces

---

changelogs/fragments/fix_lacp_interfaces_mode_facts_parsing.yaml
plugins/module_utils/network/nxos/facts/lacp_interfaces/lacp_interfaces.py
tests/unit/modules/network/nxos/test_nxos_lacp_interfaces.py

In the current lacp interface facts parser, it will parse "mode" directly for the lacp mode, which could conflict with configs like
`"switchport mode trunk"`. Add `"lacp mode"` as the conf arg parser to make the lacp mode parsing more accurate.

fix lacp interface facts parser for lacp mode

---

changelogs/fragments/161-transfer_protocol_file_copy.yaml
plugins/action/nxos_file_copy.py
plugins/modules/nxos_file_copy.py
tests/integration/targets/nxos_file_copy/meta/main.yml
tests/integration/targets/nxos_file_copy/tests/cli/input_validation.yaml
tests/integration/targets/nxos_file_copy/tests/cli/sanity.yaml

At the moment only scp can be used as a transfer protocol to pull files from a NXOS device in the nxos_file_copy module. Instead of hardcoding the protocol in the copy command, this PR will allow additional set of transfer protocols to be used. For this purpose I have introduced a new module parameter file_pull_protocol.
nxos_file_copy
I have tested the functionality after my code change with sftp, ftp and http protocols on a NXOS device with version 9.3(4) and 7.0.(3).I(7). Furthermore I have implemented two additional integration test cases to test the module with the new parameter. 
The sanity integration test will change temporarily the admin password of the NXOS device to be able to use sftp. The password of the admin user will be recovered at the end of the …

Allow other transfer protocols than scp in nxos_file_copy module.

---

changelogs/fragments/fix_nxos_ospfv2.yaml
plugins/module_utils/network/nxos/rm_templates/ospfv2.py
tests/unit/modules/network/nxos/test_nxos_ospfv2.py

- Fixes #151
- Fixes #152 
- Correctly process `log_adjacency_changes` dict while computing commands.
rm_templates/ospfv2.py

Fix rendering of log_adjacency_changes commands

---

changelogs/fragments/add_fex_fabric_l2_inteerfaces.yaml
plugins/module_utils/network/nxos/argspec/l2_interfaces/l2_interfaces.py
plugins/modules/nxos_l2_interfaces.py
tests/integration/targets/nxos_l2_interfaces/tests/common/parsed.yaml
tests/integration/targets/nxos_l2_interfaces/tests/common/rendered.yaml
tests/integration/targets/nxos_l2_interfaces/vars/main.yml

Allow for interface switchport mode to be fex-fabric, opening up
modification of other interfaces which are in trunk & access mode
Fixes #166 
nxos_l2_interfaces

Fix ansible-collections#166 - Support FEX Fabric mode on nxos_l2_interfaces

---

changelogs/fragments/vlans-fabricpath-mode-regex.yaml
plugins/module_utils/network/nxos/config/vlans/vlans.py

Update regex to accept the platform "N77" as supporting fabricpath.
N/A
Regex was failing for platforms such as "N77-C7706".

Update vlan fabricpath mode regex

---

changelogs/fragments/fix_vlan_diff.yaml
plugins/module_utils/network/nxos/config/vlans/vlans.py
tests/unit/modules/network/nxos/test_nxos_vlans.py

Fixed an issue with the vlan config generation, where default values were not being properly removed. 
When making changes to vlan config default values remained in the commands list. The code removed default values from the existing config, but not from the resulting diff. 
Tested on Nexus 7K platform.

Fix vlan config diff to remove default states

---

requirements.txt

Due to how ansible / ansible-base works we need to remove ansible here.
Otherwise, our devel jobs are testing 2.10.
Signed-off-by: Paul Belanger <pabelanger@redhat.com>

Drop ansible in requirements.txt

---

changelogs/fragments/fix_nxos_lag_interfaces.yaml
plugins/module_utils/network/nxos/config/lag_interfaces/lag_interfaces.py
tests/integration/targets/nxos_lag_interfaces/tests/common/merged.yaml

Fixes https://github.com/ansible-collections/cisco.nxos/issues/193
nxos_lag_interfaces
Integration test step added to defend against this.

Fix nxos_lag_interfaces error when no port-channel members exist

---

changelogs/fragments/fix_ospf_process_id.yaml
plugins/module_utils/network/nxos/rm_templates/ospfv2.py
plugins/module_utils/network/nxos/rm_templates/ospfv3.py
tests/unit/modules/network/nxos/test_nxos_ospfv2.py
tests/unit/modules/network/nxos/test_nxos_ospfv3.py

- Fixes #198 
rm_templates/ospfv2.py
rm_templates/ospfv3.py

Make OSPF modules work properly when process_id is a string

---

changelogs/fragments/204-improve-nxos-vxlan-vtep-module-docs.yaml
docs/cisco.nxos.nxos_vxlan_vtep_module.rst
plugins/modules/nxos_vxlan_vtep.py

Depends-On: https://github.com/ansible-collections/cisco.nxos/pull/209
This PR improves the documentation for the nxos_vxlan_vtep module. Specifically:
* Fix an error in the example where a value of `default` is used for the `host_reachability` parameter, even though the `default` value is not supported for this parameter.
* Improve the description of the `host_reachability` parameter.
* Improve the description of parameters that are applicable to specific series of switches and/or specific NX-OS software releases.
* Correct spelling/grammar where errors were noticed.
nxos_vxlan_vtep

Improve nxos_vxlan_vtep module documentation

---

changelogs/fragments/nxos_config_replace.yaml
docs/cisco.nxos.nxos_config_module.rst
plugins/cliconf/nxos.py
plugins/modules/nxos_config.py

nxos_config: let device to throw an error if config replace is not supported

---

changelogs/fragments/fix_l2_interfaces_mode_fabricpath
plugins/module_utils/network/nxos/argspec/l2_interfaces/l2_interfaces.py
plugins/modules/nxos_l2_interfaces.py
tests/integration/targets/nxos_l2_interfaces/tests/common/parsed.yaml
tests/integration/targets/nxos_l2_interfaces/tests/common/rendered.yaml
tests/integration/targets/nxos_l2_interfaces/vars/main.yml

Fixes #220
Add "fabricpath" as additional mode choice in:
cisco.nxos/plugins/module_utils/network/nxos/argspec/l2_interfaces/l2_interfaces.py
cisco.nxos/plugins/module_utils/network/nxos/argspec/l2_interfaces/l2_interfaces.py
```
nxos_facts experiences fatal error when it discovers an interface in mode "fabricpath".  Changing choices from 'access', 'trunk', 'fex-fabric' to include 'fabricpath'
```

Add "fabricpath" to mode choices for l2 interfaces ( FIX for issue #220)

---

changelogs/fragments/mask_sensitive_values.yaml
plugins/modules/nxos_aaa_server.py
plugins/modules/nxos_pim_interface.py
plugins/modules/nxos_snmp_user.py
plugins/modules/nxos_vrrp.py

- Enable no_log for sensitive parameters in argspec.
nxos_aaa_server.py
nxos_pim_interface.py
nxos_snmp_user.py
nxos_vrrp.py

Enable no_log for sensitive parameters in argspec

---

changelogs/fragments/nxos_acls.yaml
docs/cisco.nxos.nxos_acls_module.rst
plugins/module_utils/network/nxos/argspec/acls/acls.py
plugins/module_utils/network/nxos/facts/acls/acls.py
plugins/modules/nxos_acls.py
tests/unit/modules/network/nxos/test_nxos_acls.py

- For IPv6 ACLs, `echo_request` is a valid option.

nxos_acls: Add echo_request option

---

changelogs/fragments/nxos_config_diff_doc_update.yaml
plugins/modules/nxos_config.py

Fixes https://github.com/ansible-collections/ansible.netcommon/issues/189
*  Update doc
*  Add warning message for idempotent pre-requisite
nxos_config
```paste below
```

Update doc to clarify on input config pattern and add warning message

---

changelogs/fragments/nxos_snmp_community.yaml
plugins/modules/nxos_snmp_community.py
tests/integration/targets/nxos_snmp_community/tests/common/sanity.yaml

- Fixes https://github.com/ansible-collections/cisco.nxos/issues/203
nxos_snmp_community.py

nxos_snmp_community: properly handle partial matches in community string

---

changelogs/fragments/depr_bgp.yaml
meta/runtime.yml
plugins/modules/nxos_bgp.py
plugins/modules/nxos_bgp_neighbor.py
tests/sanity/ignore-2.9.txt

- Deprecate nxos_bgp and nxos_bgp_neighbor in favor of nxos_bgp_global

Deprecate legacy BGP modules

---

changelogs/fragments/237_nxos_ping_df_size.yaml
plugins/modules/nxos_ping.py

Add support size and df_bit options for `nxos_ping` module.
- `nxos_ping`
```yaml
- cisco.nxos.nxos_ping:
dest: 8.8.8.8
df_bit: true
size: 1400
vrf: management
```
executes  bellow comamnd.
```
ping 8.8.8.8 count 5 vrf management packet-size 1400 df-bit
```

Add support size and df_bit options for nxos_ping 

---

changelogs/fragments/config_module_warning_msg.yaml
plugins/modules/nxos_config.py

*  Currently the warning message for diff is thrown
for every module run.
*  Based on discussion here https://github.com/ansible/network/discussions/48
a better way of logging the message is through verbose
logs but verbose logging has a known issue https://github.com/ansible-collections/ansible.netcommon/issues/224
*  Hence moving the message under `warnings` key within the task
response if `changed=True`
nxos_config
```paste below
```

Move warning message for nxos_config module

---

changelogs/fragments/fix_hello_interval.yaml
plugins/modules/nxos_pim_interface.py
tests/unit/modules/network/nxos/test_nxos_pim_interface.py

- Fixes #226 
- The `hello_interval` value was incorrectly being multiplied by 1000. This prevents sub second intervals or interval greater than 18724 from being configured. Both of which are valid values.
- Since updating the behaviour would be a breaking change, a new option `hello_interval_ms` was added, which when set to True, prevents the `hello_interval` from being converted into milliseconds. When set to False on kept unset, the module behaves as before.
nxos_pim_interface.py

Add hello_interval_ms option in nxos_pim_interface

---

changelogs/fragments/fix_nxos_acls.yaml
plugins/module_utils/network/nxos/config/acls/acls.py
plugins/module_utils/network/nxos/facts/acls/acls.py
tests/unit/modules/network/nxos/test_nxos_acls.py

- Fixes #253
- Fixes https://github.com/ansible-collections/cisco.nxos/issues/262
- Note: The doc changes here were made by the pre-commit hook and should no longer be a part of this PR once the depends on PR is merged.
config/acls.py

Allow integer values to be set for dscp key and correctly parse non rule entries

---

changelogs/fragments/no_log_fix.yaml
plugins/module_utils/network/nxos/facts/bgp_global/bgp_global.py
plugins/module_utils/network/nxos/facts/ospf_interfaces/ospf_interfaces.py
plugins/module_utils/network/nxos/rm_templates/bgp_global.py
plugins/module_utils/network/nxos/rm_templates/ospf_interfaces.py

Depends-On: https://github.com/ansible-collections/ansible.netcommon/pull/246
- Pass current module object to validate_config() in order to update no_log_values list for proper masking.
facts/ospf_interfaces.py
facts/bgp_global.py

Properly mask values of sensitive keys in module result

---

changelogs/fragments/update_requirement.yaml
galaxy.yml

- The changes introduced in #270 are dependent on ansible.netcommon:2.0.1. This was not updated in galaxy.yml causing affected modules fail in v2.1.0 fails if the netcommon installed is <2.0.1.
- This patch bumps the requirement in galaxy.yml.
- We will need a v2.1.1 release for this collection.
galaxy.yml

Bump ansible.netcommon requirement to >=2.0.1

---

README.md
changelogs/fragments/netconf.yaml
docs/cisco.nxos.nxos_netconf.rst
plugins/netconf/nxos.py

- Add a netconf subplugin to make netconf_* modules work with older NX-OS versions.
- Fixes https://github.com/ansible-collections/ansible.netcommon/issues/252
netconf/nxos.py

Add netconf subplugin

---

2
changelogs/fragments/netconf_fix.yaml
docs/cisco.nxos.nxos_netconf.rst
docs/cisco.nxos.nxos_route_maps_module.rst
plugins/netconf/nxos.py

- Fixing the incorrect device handler name that went in with https://github.com/ansible-collections/cisco.nxos/pull/298.

netconf: change device handler to nexus 

---

changelogs/fragments/static_routes.yaml
plugins/module_utils/network/nxos/facts/static_routes/static_routes.py
tests/unit/modules/network/nxos/test_nxos_static_routes.py

Note: This is a temporary fix to let existing options provided by this module work. Adding `bfd` support requires considerable rework of the existing code and will be done in a later release.
nxos_static_routes.py

Prevent traceback when parsing unexpected line

---

changelogs/fragments/fix_ospf_interfaces.yaml
plugins/module_utils/network/nxos/facts/ospf_interfaces/ospf_interfaces.py

- Sorting the interfaces with names results in the following:
```
after:
- name: Ethernet1/1
- name: Ethernet1/10
- name: Ethernet1/11
- name: Ethernet1/12
- name: Ethernet1/13
- name: Ethernet1/14
- name: Ethernet1/2
- name: Ethernet1/3
- name: Ethernet1/4
```
- This patch makes it render in the natural order.
nxos_ospf_interfaces.py

[ospf_interfaces] Fix rendering of interface names

---

changelogs/fragments/nxos_acls.yaml
plugins/module_utils/network/nxos/facts/acls/acls.py
tests/unit/modules/network/nxos/test_nxos_acls.py

- If the remark has "ip/ipv6 access-list" in it, it was not being parsed.
- This patch fixes it.
nxos_acls.py

[acls] Fix parsing of remarks

---

changelogs/fragments/nxos_ntp.yaml
plugins/module_utils/network/nxos/rm_templates/ntp_global.py
tests/unit/modules/network/nxos/test_nxos_ntp_global.py

- Fixes #399 
nxos_ntp_global.py

[ntp_global] account for extra whitespace in source-interface line

---

changelogs/fragments/fix_nxos_vlans.yaml
plugins/module_utils/network/nxos/facts/vlans/vlans.py

Fixes https://github.com/ansible-collections/cisco.nxos/issues/425
nxos_vlans
This fix changes the fact gathering logic for handling the unstructured output that comes back for `vlan` to `vni` mapping.  The old logic did a check to see if the vlan number exists in the output which could easily match in cases where a match is not desired.  This was causing the default vlan to be changed if `1`  matched anything next to a `\n` character  in the output line

Fix default vlan state overridden issue

---

changelogs/fragments/stderr.yaml
plugins/terminal/nxos.py

Don't match all non-newline characters before `not found`.
With larger responses (>15KB), `[^\r\n]+ not found` regex search gets painfully slow.
- New Module Pull Request
`plugins/terminal/nxos.py`
When gathering facts, we get ~128KB JSON response for `show interface | json`. After 3 chunks of data above regex takes ~1s to search and timeouts even w/ a timeout of 3min (ansible-connection process takes 100% CPU on Macbook Pro 15" 2017).
```
ansible -m nxos_facts -i your-inventory.yml your-host -a 'gather_subset=all'
```
```
{
"changed": false,
"invocation": {
"module_args": {
"available_network_resources": false,
"gather_network_resources": [
"all",
"!interfaces"
],
"gather_subset": [
"all",
"!interfaces"
],
"provider": null …
```

fix slow stderr regex search

---

changelogs/fragments/ntp.yaml
plugins/terminal/nxos.py
tests/integration/targets/nxos_ntp_global/tests/common/merged.yaml

- Fixes #467 
nxos_logging_global.py

[ntp_global] fail when using missing auth key

---

changelogs/fragments/snmp_server_PR444.yaml
plugins/module_utils/network/nxos/rm_templates/snmp_server.py
tests/unit/modules/network/nxos/test_nxos_snmp_server.py

Contact and location were not gathered if containing any whitespace.
This fix changes regex to allow any character.
Fixes  #443
nxos_facts: network ressource snmp_server
```paste below
```

[snmp_server] fix (#443)

---

changelogs/fragments/min_netcommon.yaml
changelogs/fragments/netcommon_ref_update.yaml
galaxy.yml

Bumping netcommon because of dependency on these patches:
- https://github.com/ansible-collections/ansible.netcommon/pull/367
- https://github.com/ansible-collections/ansible.netcommon/pull/370

Bump min required netcommon

---

changelogs/fragments/ntp_global.yaml
plugins/module_utils/network/nxos/config/ntp_global/ntp_global.py
tests/unit/modules/network/nxos/test_nxos_ntp_global.py

- Fixes https://github.com/ansible-collections/cisco.nxos/issues/484
nxos_ntp_global.py

[ntp_global] ensure aliased keys are idempotent

---

.gitignore
changelogs/fragments/513.yaml

These two entries are necessary as a result of the new testing strategy.
- The collection folder is created with linked contents by the pytest-ansible-units plugin
- The .virl directory is a result of using virl within the source root

Add .virl and collections to gitignore

---

changelogs/fragments/520.yaml
tests/integration/targets/nxos_config/tasks/main.yaml
tests/integration/targets/nxos_install_os/tasks/main.yaml
tests/integration/targets/nxos_install_os/tasks/upgrade/copy_kick_system_images.yaml
tests/integration/targets/nxos_install_os/tasks/upgrade/install_os.yaml
tests/integration/targets/nxos_install_os/tasks/upgrade/main_os_install.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n3172_greensboro.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n3172_u61a.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n3172_u62a.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n3172_u63a.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n35_62a88.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n35_greensboro.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n5k_730_N11.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n5k_733_N11.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n7k_atherton.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n7k_helsinki.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n9k_greensboro.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n9k_greensboro_force.yaml
tests/integration/targets/nxos_install_os/tests/common/upgrade_n9k_hamilton.yaml
tests/integration/targets/nxos_nxapi/tests/cli/configure.yaml
tests/integration/targets/nxos_overlay_global/tests/common/sanity.yaml
tests/integration/targets/nxos_smoke/tasks/cli.yaml
tests/integration/targets/nxos_smoke/tasks/nxapi.yaml
tests/integration/targets/nxos_vxlan_vtep/tests/common/sanity.yaml
tests/integration/targets/nxos_vxlan_vtep_vni/tests/common/sanity.yaml

Switch from include to include_tasks
include is being deprecated in 2.16 and emit WARNINGS
- content quality
tests
Done manually

Switch to include_tasks

---

changelogs/fragments/ospf_subinterface_failure.yaml
plugins/module_utils/network/nxos/facts/ospf_interfaces/ospf_interfaces.py

When the target NXOS device has sub-interfaces, some modules like `nxos_ospf_interfaces` and `nxos_facts`, which use fact `ospf_interfaces`, fail with the following error:
```
msg: '''<'' not supported between instances of ''str'' and ''int'''
```
If the target NXOS device has sub-interfaces, these modules fail even when sub-interfaces are not mentioned in your playbook.
`plugins/module_utils/network/nxos/facts/ospf_interfaces/ospf_interfaces.py`
With PR #360 , the sorting of interfaces retrieved as a part of OSPF interfaces fact got improved. However, it introduced a bug where any modules using the said fact under the hood fail when the target device has sub-interfaces.
After the fix in this PR, fact `ospf_interfaces` won't fail even when the target NXOS device has …

fix OSPF interface related modules failing with subinterfaces

---

changelogs/fragments/nxos_facts.yaml
plugins/module_utils/network/nxos/facts/legacy/base.py

[facts] Parse module info correctly when TABLE_modinfo is a list

---

changelogs/fragments/telemetry.yaml
docs/cisco.nxos.nxos_telemetry_module.rst
plugins/module_utils/network/nxos/argspec/telemetry/telemetry.py
plugins/module_utils/network/nxos/cmdref/telemetry/telemetry.py
plugins/module_utils/network/nxos/nxos.py
plugins/module_utils/network/nxos/utils/telemetry/telemetry.py
plugins/modules/nxos_telemetry.py
tests/unit/modules/network/nxos/test_nxos_telemetry.py

- Allow destination-group & sensor-group id to be strings.
- Allow sensor-group paths to be generated without additional properties.
nxos_telemetry.py

[telemetry] assorted fixes for destination and sensor groups

---

.github/workflows/tests.yml

- Run GHA workflows at 00:00 UTC every day.
- This is an attempt to replace Zuul's periodic pipeline jobs. But this unfortunately, has the following caveat: https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/

Run GHA periodically

---

changelogs/fragments/file_copy.yaml
plugins/action/nxos.py

- The file_pull_timeout was overriding command_timeout always, even in cases where it's not supposed to.
nxos_file_copy.py

[file_copy] timeout calculation fixes

---

changelogs/fragments/fix_749.yaml
plugins/module_utils/network/nxos/config/interfaces/interfaces.py
tests/unit/modules/network/nxos/test_nxos_interfaces.py

- Fixes #749
- Supported N3K versions have L3 shutdown by default.
nxos_interfaces.py

[interfaces] correctly enable interfaces on N3K

---

changelogs/fragments/ana_442.yaml
plugins/module_utils/network/nxos/facts/static_routes/static_routes.py
plugins/module_utils/network/nxos/rm_templates/static_routes.py
tests/unit/modules/network/nxos/test_nxos_static_routes.py

- nxos_static_routes command formation is erroneous when `track` param is specified.
nxos_static_routes.py

[static_routes] correctly generate commands when track param is specified

---

changelogs/fragments/route_maps.yaml
plugins/module_utils/network/nxos/config/route_maps/route_maps.py
tests/unit/modules/network/nxos/test_nxos_route_maps.py

This commit introduces the ability to handle simple route-maps that do not contain set or match statements.
It allows for the creation and management of purely basic route-map entries like 'route-map test-1 permit 10'.
cisco.nxos.nxos_route_maps
cisco.nxos.nxos_route_maps module cannot handle following task which does not have a set, a match and a description section for now.
See also unit tests.
```
- name: Sample Task
cisco.nxos.nxos_route_maps:
config:
- route_map: rmap1
entries:
- sequence: 10
action: permit
state: merged
```
```
% pytest tests/unit/modules/network/nxos/test_nxos_route_maps.py 
========================================================== test session starts ==========================================================
platform darwin -- Python …
```

[route_maps] Enable handling of route-maps without set/match

---

changelogs/fragments/nxos_l3_interfaces.yaml
plugins/cliconf/nxos.py
plugins/module_utils/network/nxos/config/l3_interfaces/l3_interfaces.py

- Fail if encapsulation exists on a different interface.
nxos_l3_interfaces.py

[l3_interfaces] fail if encapsulation exists on a different sub-interface.

---

plugins/cliconf/nxos.py

- Mostly described in https://github.com/ansible-collections/ansible.netcommon/pull/640.
- Summary: `err_responses` cannot be added in edit_config base signature, this breaks other platforms. The fact that edit_config base has `diff` kwarg and nxos cliconf edit_config doesn't results in sanity/pylint to trip if `err_responses` isn't added in edit_config base.
cliconf/nxos.py

[cliconf] changes required after cliconfbase updates in ansible.netcommon#640

---

tests/integration/targets/nxos_facts/vars/main.yml
tests/integration/targets/nxos_vrf_global/tasks/main.yml
tests/integration/targets/nxos_vrf_global/tests/common/_check_device.yaml
tests/integration/targets/nxos_vrf_global/tests/common/_parsed.cfg
tests/integration/targets/nxos_vrf_global/tests/common/_populate_config.yaml
tests/integration/targets/nxos_vrf_global/tests/common/merged.yaml
tests/integration/targets/nxos_vrf_global/tests/common/replaced.yaml
tests/integration/targets/nxos_vrf_global/tests/common/rtt.yaml
tests/integration/targets/nxos_vrf_global/vars/main.yaml

Add vrf_global to the list of facts gathered and fixes the set_fact for management

Adds facts to list of facts and fix management fact

---

changelogs/fragments/lldp_facts.yaml
plugins/module_utils/network/nxos/facts/legacy/base.py

Fixes an issue where the LLDP neighbor information returns an error when empty.
- legacy/base.py
Fixes:
Below error when lldp neighbours empty
```json
{
"module_stdout": "",
"module_stderr": "'TABLE_nbor'",
"msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",
"_ansible_no_log": false,
"changed": false
}
```
Facts when no neighbours:
```
ansible_net_neighbors:
mgmt0:
- host: NXOS9000v(9FLFSK4RT9R)
port: mgmt0
sysname: NXOS9000v(9FLFSK4RT9R)
```
Facts when neighbours exists:
```
ansible_net_neighbors:
Ethernet1/1:
- host: NXOS9000v(9FLFSK4RT9R)
port: Ethernet1/1
sysname: NXOS9000v(9FLFSK4RT9R)
mgmt0:
- host: NXOS9000v(9FLFSK4RT9R)
port: mgmt0
sysname: NXOS9000v(9FLFSK4RT9R)
```

Handle Empty LLDP Neighbor Information in facts

---

changelogs/fragments/nxos_telemetry_overridden.yaml
changelogs/fragments/telemetry_overridden.yaml
docs/cisco.nxos.nxos_telemetry_module.rst
plugins/module_utils/network/nxos/argspec/telemetry/telemetry.py
plugins/module_utils/network/nxos/config/telemetry/telemetry.py
plugins/modules/nxos_telemetry.py
tests/unit/modules/network/nxos/test_nxos_telemetry.py

Added support for 'overridden' state to cisco.nxos.telemetry module and included corresponding test cases. The overridden state functionality behaves similarly to the replaced state, allowing users to completely override the existing telemetry configuration with their specified configuration. 
cisco.nxos.telemetry

added overridden state for cisco.nxos_telemetry

---

changelogs/fragments/nxos_l2_interfaces.yaml
plugins/module_utils/network/nxos/config/l2_interfaces/l2_interfaces.py
tests/integration/targets/nxos_l2_interfaces/tests/common/_populate_config.yaml
tests/integration/targets/nxos_l2_interfaces/tests/common/replaced.yaml

Fixes handling of "none" value in allowed_vlans configuration for nxos_l2_interfaces module. Currently, when configuring allowed_vlans: none with state: replaced, the module either fails with int conversion error or removes the VLAN configuration entirely, making the port allow all VLANs instead of setting it to none.
cisco.nxos.nxos_l2_interfaces

fix None value handling in l2 interfaces

---

changelogs/fragments/nxos_facts_cpu_utilization.yaml
plugins/module_utils/network/nxos/facts/legacy/base.py
tests/integration/targets/nxos_facts/vars/main.yml

Fixes #915 
Fixed nxos_facts gathering for hardware subset where CPU utilization parsing fails on NX-OS 9.3(3).
The issue occurs because NX-OS 9.3(3) returns CPU metrics differently than newer versions:
- NX-OS 9.3(3): `onemin_percent` is a list `["13", "12"]` 
- NX-OS 10.4+: Uses separate `onemin_percent` and `fivemin_percent` fields
-
Bugfix Pull Request
nxos_facts

Fix hardware subsets for nxos 9.3 version

---

changelogs/fragments/test_ci.yaml
plugins/modules/nxos_user.py
plugins/modules/nxos_vpc.py
tests/integration/targets/nxos_bfd_interfaces/tests/common/gathered.yaml
tests/integration/targets/nxos_bfd_interfaces/vars/main.yml
tests/integration/targets/nxos_file_copy/tests/cli/sanity.yaml
tests/integration/targets/nxos_logging_global/tests/common/merged.yaml
tests/integration/targets/nxos_logging_global/tests/common/overridden.yaml
tests/integration/targets/nxos_logging_global/tests/common/parsed.yaml
tests/integration/targets/nxos_logging_global/tests/common/rendered.yaml
tests/integration/targets/nxos_logging_global/tests/common/replaced.yaml
tests/integration/targets/nxos_logging_global/vars/main.yml
tests/integration/targets/nxos_vrf_global/tasks/main.yml
tests/integration/targets/nxos_vrf_global/tests/common/merged.yaml
tests/integration/test_integration.py

This PR fixes several things that had issue with downstream tests:
nxos_user - fixes failures caused by #903 in downstream
vrf_global - increases wait time
nxos_vpc - fixes bug where it fails due to not availability of kickstart_ver_str
nxos_logging_global - fixes incompatible commands being tested in upstream

Fix the upstream test failures due to device image upgrade

---

changelogs/fragments/ci_logging_global.yaml
tests/integration/targets/nxos_logging_global/tests/common/deleted.yaml
tests/integration/targets/nxos_logging_global/tests/common/gathered.yaml
tests/integration/targets/nxos_logging_global/tests/common/merged.yaml
tests/integration/targets/nxos_logging_global/tests/common/overridden.yaml
tests/integration/targets/nxos_logging_global/tests/common/replaced.yaml
tests/integration/targets/nxos_logging_global/vars/main.yml

Fixes logging global downstream
- Test fix

Fixes logging global downstream
